spring.application.name=betacom

#konfiguracja run application
#spring.datasource.url=jdbc:mysql://localhost:3306/notes_db?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
#konfiguracja dockerowa
spring.datasource.url=jdbc:mysql://mysql-db:3306/notes_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

#Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

#jwtToken
#token wygasnie po 60 minutach
jwtToken.expirationTime=3600000
jwt.secret=oA15OoJIyBW0htmfRWsoXdtzPvOK7ris82gIpdUPmcqgUKbgOUUEqlHuQGNz2Go

# Rate Limiting Configuration
#ilosc prob logowania
rate-limit.capacity=5
#czas w sekundach do odnowienia prob logowania
rate-limit.interval-seconds=60